"use client";

import { useState } from "react";
import {
  CheckCircle2,
  ChevronDown,
  ChevronUp,
  Copy,
  Check,
  Download,
  Eye,
  EyeOff,
  Sparkles,
} from "lucide-react";
import jsPDF from "jspdf";

interface Question {
  questionText: string;
  answerA: string;
  answerB: string;
  answerC: string;
  answerD: string;
  correctAnswer: string;
  explanation: string;
}

interface QuizDisplayProps {
  questions: Question[];
  title: string;
}

const optionLabels = ["A", "B", "C", "D"] as const;
const optionKeys = ["answerA", "answerB", "answerC", "answerD"] as const;

export function QuizDisplay({ questions, title }: QuizDisplayProps) {
  const [showAnswers, setShowAnswers] = useState(true);
  const [expandedExplanations, setExpandedExplanations] = useState<Set<number>>(new Set());
  const [copied, setCopied] = useState(false);

  const toggleExplanation = (index: number) => {
    setExpandedExplanations((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(index)) {
        newSet.delete(index);
      } else {
        newSet.add(index);
      }
      return newSet;
    });
  };

  const copyToClipboard = async () => {
    const text = questions
      .map((q, i) => {
        const lines = [
          `Q${i + 1}. ${q.questionText}`,
          `  A) ${q.answerA}`,
          `  B) ${q.answerB}`,
          `  C) ${q.answerC}`,
          `  D) ${q.answerD}`,
          `  Correct Answer: ${q.correctAnswer}`,
          `  Explanation: ${q.explanation}`,
        ];
        return lines.join("\n");
      })
      .join("\n\n");

    const fullText = `${title}\n${"=".repeat(title.length)}\n\n${text}`;

    try {
      await navigator.clipboard.writeText(fullText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      const textarea = document.createElement("textarea");
      textarea.value = fullText;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    let y = 20;

    // Title
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    const titleLines = doc.splitTextToSize(title, maxWidth);
    doc.text(titleLines, margin, y);
    y += titleLines.length * 8 + 4;

    // Subtitle
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 120, 120);
    doc.text(`${questions.length} Questions • Generated by QuizBuilder AI`, margin, y);
    doc.setTextColor(0, 0, 0);
    y += 12;

    // Separator
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    questions.forEach((q, i) => {
      if (y > 250) {
        doc.addPage();
        y = 20;
      }

      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      const qLines = doc.splitTextToSize(`${i + 1}. ${q.questionText}`, maxWidth);
      doc.text(qLines, margin, y);
      y += qLines.length * 5.5 + 4;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      optionLabels.forEach((label, oi) => {
        const key = optionKeys[oi];
        const isCorrect = q.correctAnswer === label;
        const prefix = isCorrect ? `✓ ${label})` : `   ${label})`;
        const optionLines = doc.splitTextToSize(`${prefix} ${q[key]}`, maxWidth - 5);

        if (isCorrect) {
          doc.setFont("helvetica", "bold");
          doc.setTextColor(22, 163, 74);
        }

        doc.text(optionLines, margin + 5, y);
        y += optionLines.length * 4.5 + 2;

        if (isCorrect) {
          doc.setFont("helvetica", "normal");
          doc.setTextColor(0, 0, 0);
        }
      });

      y += 2;
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      const expLines = doc.splitTextToSize(`Explanation: ${q.explanation}`, maxWidth - 5);
      doc.text(expLines, margin + 5, y);
      doc.setTextColor(0, 0, 0);
      y += expLines.length * 4 + 10;
    });

    doc.save(`${title.replace(/[^a-zA-Z0-9 ]/g, "").replace(/\s+/g, "_")}.pdf`);
  };

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="bg-[#111114] rounded-2xl border border-[#1e1e26] p-5">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="p-2.5 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl text-white shadow-lg shadow-indigo-500/20">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white leading-tight">{title}</h2>
              <p className="text-sm text-gray-500 mt-0.5">
                {questions.length} question{questions.length !== 1 ? "s" : ""} generated
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowAnswers(!showAnswers)}
              className="flex items-center gap-2 px-3 py-2 text-sm font-medium rounded-lg border border-[#2a2a35] text-gray-400 hover:text-white hover:bg-[#1a1a22] transition-colors"
            >
              {showAnswers ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
              {showAnswers ? "Hide" : "Show"}
            </button>
            <button
              onClick={copyToClipboard}
              className="flex items-center gap-2 px-3 py-2 text-sm font-medium rounded-lg border border-[#2a2a35] text-gray-400 hover:text-white hover:bg-[#1a1a22] transition-colors"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              {copied ? "Copied!" : "Copy"}
            </button>
            <button
              onClick={downloadPDF}
              className="flex items-center gap-2 px-3 py-2 text-sm font-medium rounded-lg bg-gradient-to-r from-indigo-500 to-purple-600 text-white hover:from-indigo-400 hover:to-purple-500 transition-all shadow-md shadow-indigo-500/20"
            >
              <Download className="w-4 h-4" />
              PDF
            </button>
          </div>
        </div>
      </div>

      {/* Questions */}
      <div className="space-y-4">
        {questions.map((q, i) => {
          const isExplanationOpen = expandedExplanations.has(i);
          return (
            <div
              key={i}
              className="bg-[#111114] rounded-2xl border border-[#1e1e26] overflow-hidden transition-all hover:border-[#2a2a35]"
            >
              {/* Question Header */}
              <div className="p-5 pb-4">
                <div className="flex gap-3.5">
                  <div className="flex-shrink-0 w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600 text-white text-sm font-bold flex items-center justify-center shadow-md shadow-indigo-500/20">
                    {i + 1}
                  </div>
                  <p className="text-gray-200 font-medium leading-relaxed pt-0.5">{q.questionText}</p>
                </div>
              </div>

              {/* Options */}
              <div className="px-5 pb-4 grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                {optionLabels.map((label, oi) => {
                  const key = optionKeys[oi];
                  const isCorrect = q.correctAnswer === label;
                  const showCorrectHighlight = showAnswers && isCorrect;

                  return (
                    <div
                      key={label}
                      className={`flex items-start gap-2.5 p-3 rounded-xl border transition-all ${
                        showCorrectHighlight
                          ? "bg-emerald-500/10 border-emerald-500/30"
                          : "bg-[#0e0e12] border-[#1e1e26]"
                      }`}
                    >
                      <span
                        className={`flex-shrink-0 w-6 h-6 rounded-md text-xs font-bold flex items-center justify-center mt-0.5 ${
                          showCorrectHighlight
                            ? "bg-emerald-500 text-white"
                            : "bg-[#1e1e26] text-gray-500"
                        }`}
                      >
                        {showCorrectHighlight ? (
                          <CheckCircle2 className="w-3.5 h-3.5" />
                        ) : (
                          label
                        )}
                      </span>
                      <span
                        className={`text-sm leading-relaxed ${
                          showCorrectHighlight ? "text-emerald-300 font-medium" : "text-gray-400"
                        }`}
                      >
                        {q[key]}
                      </span>
                    </div>
                  );
                })}
              </div>

              {/* Explanation Toggle */}
              {showAnswers && (
                <div className="border-t border-[#1e1e26]">
                  <button
                    onClick={() => toggleExplanation(i)}
                    className="flex items-center justify-between w-full px-5 py-3 text-sm text-gray-500 hover:text-gray-300 hover:bg-[#0e0e12] transition-colors"
                  >
                    <span className="font-medium">
                      {isExplanationOpen ? "Hide Explanation" : "Show Explanation"}
                    </span>
                    {isExplanationOpen ? (
                      <ChevronUp className="w-4 h-4" />
                    ) : (
                      <ChevronDown className="w-4 h-4" />
                    )}
                  </button>
                  {isExplanationOpen && (
                    <div className="px-5 pb-4">
                      <div className="p-3.5 bg-indigo-500/10 rounded-xl border border-indigo-500/20">
                        <p className="text-sm text-indigo-300 leading-relaxed">{q.explanation}</p>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
